name: Selekcja

on:
  push:
    paths:
      - 'zdjecia/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  selekcja:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Instalacja
        run: pip install opencv-python-headless numpy
      
      - name: Uruchom selekcję
        run: python selekcja.py
      
      - name: Commit zmian w zdjecia_czekajace/
        run: |
          git add zdjecia_czekajace/
          git diff --quiet && git diff --staged --quiet || git commit -m "Przeniesiono zdjęcie do zdjecia_czekajace/"
      
      - name: Push zmian
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git pull --rebase origin main || true
          git push origin main
