name: AI

on:
  push:
    paths:
      - 'zdjecia_czekajace/**'
  workflow_dispatch:

jobs:
  ai:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: echo "WORKFLOW ODPALONY"
      - run: ls -la zdjecia_czekajace/
