name: AI

on:
  push:
    paths:
      - 'zdjecia_czekajace/*.jpg'
      - 'zdjecia_czekajace/*.jpeg'
      - 'zdjecia_czekajace/*.png'

jobs:
  ai:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: pip install tensorflow opencv-python-headless numpy
      - run: python ai_z_modelem.py
      - run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add zdjecia_czekajace/ zdjecia_gotowe/ data/parking.json
          git diff --quiet && git diff --staged --quiet || git commit -m "AI auto"
          git push
