name: Analiza zdjęć

on:
  push:
    paths:
      - 'zdjecia/*'  # Uruchamia się gdy dodajesz zdjęcie

jobs:
  analizuj:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Uruchom skrypt
        run: python skrypt.py
      
      - name: Zapisz zmiany
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/parking.json
          git commit -m "Auto aktualizacja z zdjęcia"
          git push
